server:
  port: 8082

spring:
  application:
    name: QUESTION-SERVICE   # MUST be unique!
  datasource:
    url: jdbc:postgresql://localhost:5433/quizdb
    username: postgres
    password: Hyder@014
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
